version: '3'

services:
  db:
    image: 'mongo:3.6.2-jessie'
  app:
    image: a-joke-statistic
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3131:3131
    depends_on: db